### ISSUE TITLE
Sections get out of order, fold markers in place

### ISSUE THREAD

**Issue by kattrali** [kattrali/xcpretty-travis-formatter#1]
[Example build](https://travis-ci.org/kattrali/xcpretty-travis-formatter/jobs/52963038)

[Raw output](https://s3.amazonaws.com/archive.travis-ci.org/jobs/52963038/log.txt)

**Comment by kattrali** [comment]
Possibly sorted this out in `0.0.2`

**Comment by jhersh** [comment]
This is really neat @kattrali! Would you consider adding a screenshot or a link to a sample travis build (or both) to the readme?

**Comment by kattrali** [comment]
@jhersh I knew I forgot something! good idea. :smile:
