### ISSUE TITLE
Feature request - periodically echo a dot to keep the job alive

### ISSUE THREAD

**Issue by weitjong** [kattrali/xcpretty-travis-formatter#4]
I have a little problem in my project Travis CI build when using the `xcpretty` to filter the Xcode output. While compiling for `glew.c` for GLEW library, there could be no output to the Travis CI's log for more than 10 minutes. As the result Travis CI may erroneously think the CI job has stalled and killed the job. I find this formatter as I am searching for a solution to my problem. Basically I need a formatter which periodically (configurable) echos a dot or other character (configurable) to the Travis CI's log to keep the job alive. Could this be done? Thank you.

**Comment by SantiagoLazzari** [comment]
@weitjong Use [travis_wait](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)

**Comment by weitjong** [comment]
Thanks for replying. We have solved this issue by our own by echoing a dot in a separate Ruby thread. We have evaluated ```travis_wait``` at that time and found it to be not suitable for our need.
